version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: udemy_db
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    environment:
      POSTGRES_DB: udemy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d udemy_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9005:9005"      # API port
      - "9001:9001"      # Web Console port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: udemyminioAdmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001" --address ":9005"

volumes:
  postgres_data:
  minio_data: